---
default: &default
  cloud_name: <%= ENV.fetch("CLOUDINARY_CLOUD_NAME") %>
  api_key: <%= ENV.fetch("CLOUDINARY_API_KEY") %>
  api_secret: <%= ENV.fetch("CLOUDINARY_API_SECRET") %>
  enhance_image_tag: true
  static_image_support: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  static_image_support: true