default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("APP_DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("APP_DB_PORT") { 54320 } %>
  username: <%= ENV.fetch('APP_DB_USER') {'pg'}%>
  password: <%= ENV.fetch('APP_DB_PASSWORD') {'123456'}%>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: anjos_do_bem_dev

test:
  <<: *default
  database: anjos_do_bem_test

production:
  <<: *default
  database: anjos_do_bem
